// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Database;

#nullable disable

namespace Movies.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movies.Shared.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "director");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "year");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Nazariusz Szeląg",
                            Title = "attitude-oriented",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            Director = "Estera Żmuda",
                            Title = "Gorgeous Granite Shirt",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Director = "Piotr Buczkowski",
                            Title = "orange",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Director = "Józefina Wiśniewski",
                            Title = "Summit",
                            Year = 2022
                        },
                        new
                        {
                            Id = 5,
                            Director = "Aleksy Pilch",
                            Title = "calculating",
                            Year = 2023
                        },
                        new
                        {
                            Id = 6,
                            Director = "Gabriela Izdebski",
                            Title = "Solutions",
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            Director = "Olaf Marek",
                            Title = "Analyst",
                            Year = 2023
                        },
                        new
                        {
                            Id = 8,
                            Director = "Hubert Skalski",
                            Title = "generating",
                            Year = 2023
                        },
                        new
                        {
                            Id = 9,
                            Director = "Elżbieta Pietrzak",
                            Title = "tan",
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            Director = "Regina Pilarski",
                            Title = "bus",
                            Year = 2023
                        },
                        new
                        {
                            Id = 11,
                            Director = "Dina Żyła",
                            Title = "transparent",
                            Year = 2023
                        },
                        new
                        {
                            Id = 12,
                            Director = "Prokles Winiarski",
                            Title = "Realigned",
                            Year = 2023
                        },
                        new
                        {
                            Id = 13,
                            Director = "Teodor Barański",
                            Title = "Refined Fresh Bacon",
                            Year = 2023
                        },
                        new
                        {
                            Id = 14,
                            Director = "Sylwia Stępniak",
                            Title = "benchmark",
                            Year = 2023
                        },
                        new
                        {
                            Id = 15,
                            Director = "Mateusz Przybyła",
                            Title = "upward-trending",
                            Year = 2023
                        },
                        new
                        {
                            Id = 16,
                            Director = "Laurencja Dziedzic",
                            Title = "Cotton",
                            Year = 2023
                        },
                        new
                        {
                            Id = 17,
                            Director = "Wanesa Kałuża",
                            Title = "digital",
                            Year = 2022
                        },
                        new
                        {
                            Id = 18,
                            Director = "Damian Buczkowski",
                            Title = "mindshare",
                            Year = 2022
                        },
                        new
                        {
                            Id = 19,
                            Director = "Ariadna Bujak",
                            Title = "functionalities",
                            Year = 2022
                        },
                        new
                        {
                            Id = 20,
                            Director = "Tomasz Czerwiński",
                            Title = "withdrawal",
                            Year = 2023
                        },
                        new
                        {
                            Id = 21,
                            Director = "Karolina Rybak",
                            Title = "connect",
                            Year = 2022
                        },
                        new
                        {
                            Id = 22,
                            Director = "Patrycy Tomczak",
                            Title = "JSON",
                            Year = 2023
                        },
                        new
                        {
                            Id = 23,
                            Director = "Gabriela Drozd",
                            Title = "New Mexico",
                            Year = 2023
                        },
                        new
                        {
                            Id = 24,
                            Director = "Greta Szymczyk",
                            Title = "Oregon",
                            Year = 2023
                        },
                        new
                        {
                            Id = 25,
                            Director = "Bibiana Lasota",
                            Title = "programming",
                            Year = 2023
                        },
                        new
                        {
                            Id = 26,
                            Director = "Janina Gałka",
                            Title = "deposit",
                            Year = 2023
                        },
                        new
                        {
                            Id = 27,
                            Director = "Walery Kaczmarczyk",
                            Title = "Tactics",
                            Year = 2022
                        },
                        new
                        {
                            Id = 28,
                            Director = "Lucjan Rojek",
                            Title = "maximize",
                            Year = 2023
                        },
                        new
                        {
                            Id = 29,
                            Director = "Ernest Adamus",
                            Title = "Florida",
                            Year = 2023
                        },
                        new
                        {
                            Id = 30,
                            Director = "Katarzyna Frątczak",
                            Title = "complexity",
                            Year = 2023
                        },
                        new
                        {
                            Id = 31,
                            Director = "Tomasz Domagała",
                            Title = "Montana",
                            Year = 2023
                        },
                        new
                        {
                            Id = 32,
                            Director = "Ruta Majewski",
                            Title = "Planner",
                            Year = 2023
                        },
                        new
                        {
                            Id = 33,
                            Director = "Berta Kalisz",
                            Title = "Borders",
                            Year = 2023
                        },
                        new
                        {
                            Id = 34,
                            Director = "Teodora Kulig",
                            Title = "Refined Plastic Table",
                            Year = 2023
                        },
                        new
                        {
                            Id = 35,
                            Director = "Patrycy Niemczyk",
                            Title = "groupware",
                            Year = 2023
                        },
                        new
                        {
                            Id = 36,
                            Director = "Robert Noga",
                            Title = "unleash",
                            Year = 2023
                        },
                        new
                        {
                            Id = 37,
                            Director = "Alan Prokop",
                            Title = "Greenland",
                            Year = 2023
                        },
                        new
                        {
                            Id = 38,
                            Director = "Beniamin Owczarek",
                            Title = "Nepalese Rupee",
                            Year = 2023
                        },
                        new
                        {
                            Id = 39,
                            Director = "Franciszek Kujawski",
                            Title = "Administrator",
                            Year = 2023
                        },
                        new
                        {
                            Id = 40,
                            Director = "Lucjan Korzeniowski",
                            Title = "alarm",
                            Year = 2023
                        },
                        new
                        {
                            Id = 41,
                            Director = "Jerzy Szymczak",
                            Title = "didactic",
                            Year = 2022
                        },
                        new
                        {
                            Id = 42,
                            Director = "Albert Jezierski",
                            Title = "Handmade",
                            Year = 2022
                        },
                        new
                        {
                            Id = 43,
                            Director = "Herman Kujawa",
                            Title = "Turnpike",
                            Year = 2022
                        },
                        new
                        {
                            Id = 44,
                            Director = "Grzegorz Włodarczyk",
                            Title = "Gorgeous Steel Table",
                            Year = 2023
                        },
                        new
                        {
                            Id = 45,
                            Director = "Izajasz Jankowski",
                            Title = "infomediaries",
                            Year = 2023
                        },
                        new
                        {
                            Id = 46,
                            Director = "Apollinary Marzec",
                            Title = "European Unit of Account 17(E.U.A.-17)",
                            Year = 2023
                        },
                        new
                        {
                            Id = 47,
                            Director = "Klara Kozak",
                            Title = "instruction set",
                            Year = 2023
                        },
                        new
                        {
                            Id = 48,
                            Director = "Edwin Jankowski",
                            Title = "Unbranded Steel Table",
                            Year = 2023
                        },
                        new
                        {
                            Id = 49,
                            Director = "Teodora Szostak",
                            Title = "Rapids",
                            Year = 2022
                        },
                        new
                        {
                            Id = 50,
                            Director = "Ryszard Mroczek",
                            Title = "Cotton",
                            Year = 2023
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
